spring:
  application:
    name: forohub
  datasource:
    url: jdbc:postgresql://${DB_HOST}/forohub
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    Hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
hibernate:
  dialect: org.hibernate.dialect.HSQLDialect
server:
  port: 8082